### ISSUE TITLE
Unable to launch jar

### ISSUE THREAD

**Issue by Fuitad** [DizzyThermal/TKViewer#10]
Hey there! Wanted to try your Java version but I'm hitting a wall.

After running mvn clean and mvn package, here's the error I get:

```
➜  TKViewer-master java -jar target/TKViewer-0.0.1-SNAPSHOT.jar
Error: Could not find or load main class com.gamemode.tkviewer.TKViewer
Caused by: java.lang.ClassNotFoundException: com.gamemode.tkviewer.TKViewer
➜  TKViewer-master java -jar target/original-TKViewer-0.0.1-SNAPSHOT.jar
no main manifest attribute, in target/original-TKViewer-0.0.1-SNAPSHOT.jar
```

I'm running the latest OSX. Do you have any idea what I'm doing wrong?

**Comment by Fuitad** [comment]
I was able to launch it using IntelliJ. Awesome app!

**Comment by DizzyThermal** [comment]
Perfect, there is likely just an issue with targeting the Main class in the
Maven POM file. Glad you got it working though :)

**Comment by DizzyThermal** [comment]
Retried using maven to build:

```
mvn clean
mvn package
```

Was built successfully on my end. Maybe OSX needs something else to resolve the path to the Main class. I'm not sure

**Comment by DizzyThermal** [comment]
Wasn't OSX related, was a POM file issue - should be resolved now
