### ISSUE TITLE
More about PAL

### ISSUE THREAD

**Issue by DDeokk** [DizzyThermal/TKViewer#2]
About header

byte PaletteMagicWord[10] ="DLPalette";
byte unknown[14];
byte numberOfColorsForAnimation;
byte unknown2[7];
byte ColorAnimationOffset[2 * numberOfColorsForAnimation];

**Comment by DizzyThermal** [comment]
Ahhh, so the "DLPalette" header that was being considered as "32 bytes" actually contains information about how the tiles animate.

That's true, Nexus tiles do glow/animate.

I presume that a PAL would define the "number" of additional palette files to cycle through (numberOfColorsForAnimation) and have a list of the PAL indicies to use/cycle through (ColorAnimationOffset).

Thanks again @DDeokk for providing this, much appreciated!

**Comment by DizzyThermal** [comment]
Commits: [03c9f2](https://github.com/DizzyThermal/EPFViewer/commit/03c9f2dee05aefa4f95a01ebee9b5e1b3bb26d80) and [d9db82d](https://github.com/DizzyThermal/EPFViewer/commit/d9db82dff70d8656959bf74804b91d5939eb4b71) implement this additional header information.
