### ISSUE TITLE
Support for map tiles and map objects 

### ISSUE THREAD

**Issue by nodren** [DizzyThermal/TKViewer#21]
I'd love to see support for both of these in tkviewer!

**Comment by rbcastner** [comment]
Can you be more specific? I know I have used this software in the past to dump the base images to a folder (of objects, map tiles, spell animations, etc), is that what you are looking for?

**Comment by DizzyThermal** [comment]
How I'd imagine this working in TKViewer:

First open the map you want to view tiles/objects on:

**File > Open > Map File (\*.cmp | \*.map)**

On the rendered map window, we could add new Menu Items:

**View > Static Objects**
**View > Tiles**

On click, a new window could open listing the unique tiles/objects w/ maybe a (# tile/object count per unique tile/object). Each with a Right-click to Save or a separate Export Button - whatever makes sense.

Thoughts?

**Comment by nodren** [comment]
is there a version of TKViewer i can download to see this new feature?
