### ISSUE TITLE
Support for legend icons?

### ISSUE THREAD

**Issue by notmayo** [DizzyThermal/TKViewer#22]
Hello, is it possible to view legend icons? I saw someone was able to view inv icons as well, but I couldn't figure that one out.

**Comment by DizzyThermal** [comment]
@notmayo added initial support for legend icons (SYMBOLS.EPF) in pull: https://github.com/DizzyThermal/TKViewer/pull/23

Note: Color may not be correct for all icons - I guessed that the color palette came from **char.dat > ITEM.PAL**, but the Symbols themselves were located in **misc.dat > SYMBOLS.EPF**

Find this under **View > Misc > Legend Resources** in the latest release:
https://github.com/DizzyThermal/TKViewer/releases/tag/3.5

**Comment by notmayo** [comment]
Wow man. Thank you so much, and I have been trying to figure out all day what the other world map names are so thanks for that too!
