### ISSUE TITLE
EPF/PAL Animations

### ISSUE THREAD

**Issue by DizzyThermal** [DizzyThermal/TKViewer#29]
Many graphics in NTK have animations. This includes map tiles/objects, character items/weapons/armor, and monsters.

In order to achieve this, my current assumption is that the palette index OR the entire palette itself must be changed.

#2 talks about the PAL header containing an animation count and an array of animation offsets, however, it wasn't clear exactly how to implement this.

Creating this issue to brainstorm approaches - all ideas welcome!

**Comment by DizzyThermal** [comment]
Using the [**Masters ward**](https://nexusatlas.com/armor/shields.php) as reference:
![mastersward](https://github.com/DizzyThermal/TKViewer/assets/730767/a34fac70-5781-4bb4-b23e-6349e46f4db0)

**EPF**: shield0.dat:Shield0.epf
**PAL**: char.dat:Shield.pal

After dumping all the EPF frames, I see 20 frames (using Palette[0]):
![image](https://github.com/DizzyThermal/TKViewer/assets/730767/dbca67d0-f264-4a62-8b73-22959e4fc203)

Focusing on Frame 129 (Front-face of the shield):
![Shield0 epf-129](https://github.com/DizzyThermal/TKViewer/assets/730767/84044f5b-83a4-4f92-84df-ccfa9d54f472)

Shield.pal has 22 palettes, so if I scrub the palette from 0-21 for Frame 129, I get:
![image](https://github.com/DizzyThermal/TKViewer/assets/730767/781ff371-b4ea-474a-a596-54deeaa90bf2)

I don't think that simply changing the palette index will achieve the color animation of NTK/Baram.

Maybe the palette index _itself_ doesn't change, but the color within the palette changes - not sure.

**EPF/PAL TL;DR:**
A palette is an array of 256 colors.. EPFs - for every pixel - point to a particular color within a palette. So each "pixel" in an EPF is 1 byte (0-0xFF -- opposed to 4-bytes rr/gg/bb/aa) pointing to a color within the 256-color palette.. I've never nailed down the correct industry term for this graphics format, maybe Indexed Color Palette?

Anyways, just some notes..

**Comment by DizzyThermal** [comment]
I tried to shift through all the colors of the first palette and wound up with these 256 frames:
![image](https://github.com/DizzyThermal/TKViewer/assets/730767/b81e716f-47b7-4dd2-9e56-ae452b94bd2e)

If there's 8 frames in the animation, I'd think 256 colors / 8 frames = 32 color offset, but if I do that it doesn't seem to work:
![image](https://github.com/DizzyThermal/TKViewer/assets/730767/58e99872-adb2-4db5-aa23-9a366a708b07)

I think I'm getting close..

**Comment by DizzyThermal** [comment]
Created a topic on ResHax.com to get some hopefully get some collaboration going :)

https://reshax.com/topic/375-nexustk-epfpal-frame-color-animations/

**Comment by zaventh** [comment]
Looks like you solved this. Perhaps those findings has implications for #27 as well. I took a look at it for a bit but this was my first time really delving deep into these file formats so I didn't get too far. Maybe I could borrow those fancy tools you have? 🙂

**Comment by DizzyThermal** [comment]
I need to breakout the file formats and EPFViewer into its own project, but I do intend on open sourcing the tools 😁

I think the "missing colors" might just be color offsets - on top of cycling the palettes. I still haven't found the perfect "Merchant armor" color.

I'm going to try to do this sometime this week, work got busy - stay tuned!

**Comment by DizzyThermal** [comment]
What I wanted to know animation loops was figured out and implemented in this Godot 4.x project:
https://github.com/DizzyThermal/EPFViewer

Closing the issue
