### ISSUE TITLE
How to run nexus tk viewer?

### ISSUE THREAD

**Issue by Chevrolet3** [DizzyThermal/TKViewer#30]
i can't find nexustkviewer.exe 
help me,, i'm korean
i can't speak english wel,,

**Comment by rbcastner** [comment]
1. In java, jar file replaces exe file.
2. Download java 8 (I use Amazon corretto java on Windows, you don't have to use Oracle java)
3. Download maven from apache
4. Download repository
5. Follow commands in readme

**Comment by Chevrolet3** [comment]
thank you for reply,, and
do you know how to run EPFViewer?
https://github.com/DizzyThermal/EPFViewer

![스크린샷 2024-04-13 162950](https://github.com/DizzyThermal/TKViewer/assets/163837466/ca77568f-d613-41fb-9fca-92778953aaf1)

I don't know what to do next step,,
i can't click epf file pal file and
How do I load it? thank you dude,,
