### ISSUE TITLE
Object transparent issue

### ISSUE THREAD

**Issue by asdqwe3124** [DizzyThermal/TKViewer#9]
Some objects aren't transparent

https://i.imgur.com/stE6GY3.png

add this **[0xC4, 0xA3, 0xBC]** RGB hex to _ALPHA_COLORS list will fix the issue

**Comment by DizzyThermal** [comment]
I need to find a better way to render transparency. I feel as if there is a alpha index/key somewhere that I'm overlooking. This ALPHA_COLORS look-up table _works_, but it is far from efficient. Thanks for grabbing another RGB value in the meantime :)  If you find anything related to transparency, please let me know and I'll dig into it more!
